## Introduction

A single computer, running a single process, behaves deterministically under controlled conditions: a given program, given the same input, produces the same output in a predictable amount of time, unless the machine itself fails outright. Distributed systems forfeit this comfort. The moment a computation is spread across more than one machine, the system inherits uncertainty (what happened, and in what order?), variability (how long will this take?), and interdependence (what does one node need from another to make progress?) as first-class engineering concerns.

This paper approaches distributed systems by deliberately not confronting all of these concerns at once. We begin from an idealized baseline: a single, deterministic machine operating under perfect conditions, with infinite computational resources, zero latency, and complete immunity to failure. Under this baseline, a distributed system collapses into ordinary sequential computing, and there is nothing distinctive to say about it. From this ideal foundation, we relax the underlying assumptions one at a time. Each relaxation introduces exactly one new real-world constraint; we examine the problems that the constraint creates, and progressively develop the solutions, mechanisms, and trade-offs that the distributed systems literature has produced in response. Because assumptions are relaxed one at a time rather than all at once, the interactions between successive constraints and the core desirable system properties (consistency, availability, latency, and fault tolerance) become traceable rather than tangled. This progression echoes the well-known Fallacies of Distributed Computing, the observation that engineers routinely design as though the network were reliable, latency were zero, and bandwidth infinite. Where the fallacies name a set of independent false beliefs, the assumptions developed here are deliberately ordered so that each relaxation builds on the last, and they extend beyond networking to cover storage economics, data volume, and throughput as well.

The objective of this work is to weave the standard concepts of distributed systems into a single logical, interconnected narrative, rather than presenting them as a catalogue of loosely related mechanisms. It aims to provide both breadth of coverage and conceptual coherence, and the chapter-by-chapter ordering is itself a pedagogical choice: each mechanism is introduced only once the constraint that necessitates it has been established, so that it arrives as an answer to a specific problem rather than an isolated fact.

For new readers, this document is intended as a conceptual roadmap: a structured way to navigate distributed systems by seeing how practical realities reshape the idealized model, chapter by chapter.

For experienced practitioners, it is intended as a refresher through a different lens, one that connects already-familiar mechanisms through a single, unifying framework of assumption relaxation and constraint introduction.

Readers are encouraged to consult the works referenced at the end of this document for a deeper, implementation-level treatment of any individual topic, and to use this document primarily as a conceptual scaffold for system-design thinking rather than as an implementation guide.

---
